name: Export NPM Token

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Write NPM token
        run: |
          mkdir -p secret
          printf '%s' "${{ secrets.NPM_TOKEN }}" > secret/NPM_TOKEN
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-token
          path: secret/NPM_TOKEN
